---
- name: Stop and Disable ufw service if started
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Stop and Disable postfix service if started
  ansible.builtin.service:
    name: postfix
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Make timout configuration file.
  template:
    src: timout.j2
    dest: /etc/profile.d/timout-settings.sh

- name: Set timezone
  community.general.timezone:
    name: '{{ server_timezone | default("Asia/Tehran") }}'
  notify: Restart ntp

- name: Copy ssh banner file.
  copy:
    src: ssh_banner
    dest: /etc/issue

- name: Make sshd configuration file.
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart ssh

- name: Set authorized key from local file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Make iptables configuration file.
  template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4

- name: restore iptables state from a file
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
    noflush: true
  notify: Restart iptables

- name: Make fail2ban configuration file.
  template:
    src: fial2ban.j2
    dest: /etc/fail2ban/jail.local
  notify: Restart fail2ban